security:
  token:
    secret: mysecret-which-needs-to-be-of-at-least-512bit-long!please-change

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 21MB
